### PR TITLE
Refactor Dockerfile

### PR DESCRIPTION
**Pull request by kin0992**
Update Dockerfile so the command `docker build -t b2b-portals -f apps/strapi-cms/Dockerfile --rm .` works.

Running that command from the root of the repository, the build completes successfully.

> **Warning**
> Once you have completed the build, if you run the container, you will get the following error:
> 
>```[2023-11-09 17:32:44.150] debug: ⛔️ Server wasn't able to start properly.
>[2023-11-09 17:32:44.154] error: Could not load js config file /opt/app/node_modules/@strapi/plugin-upload/strapi->server.js: 
>Something went wrong installing the "sharp" module
>```

> **Note**
> Some useful information about the error can be found here: https://forum.strapi.io/t/facing-error-on-installation-of-strapi-something-went-wrong-installing-the-sharp-module/16420/27

#### List of Changes

- Create the `ts-config` package
- Use `turbo prune` command to create a pruned version of the monorepo
- Update Dockerfile
- Remove `tsconfig.json` from the root of the repository

#### Motivation and Context

The `docker build` command of the PR #33 is not working

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kin0992** [comment]
@maurodandrea I made some changes about the Dockerfile to let the `docker build` command work.
I may have changed some details within the Dockerfile, but feel free to change everything you think can be improved.
My intention here was to fix the issues during the build.

Now we are having a problem when running the container. Maybe you and @simosalsi already saw that issue.

**Comment by maurodandrea** [comment]
gives me this error too:

[2023-11-09 19:20:22.481] debug: ⛔️ Server wasn't able to start properly.
[2023-11-09 19:20:22.500] error: Could not load js config file /opt/app/node_modules/@strapi/plugin-upload/strapi-server.js:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linuxmusl-x64.node'
Require stack:
- /opt/app/node_modules/sharp/lib/sharp.js
- /opt/app/node_modules/sharp/lib/constructor.js
- /opt/app/node_modules/sharp/lib/index.js
- /opt/app/node_modules/@strapi/plugin-upload/server/services/image-manipulation.js
- /opt/app/node_modules/@strapi/plugin-upload/server/services/index.js
- /opt/app/node_modules/@strapi/plugin-upload/server/index.js
- /opt/app/node_modules/@strapi/plugin-upload/strapi-server.js
- /opt/app/node_modules/@strapi/utils/dist/import-default.js
- /opt/app/node_modules/@strapi/utils/dist/index.js
- /opt/app/node_modules/@strapi/strapi/lib/services/entity-service/components.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/queries/entity.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/queries/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/providers/local-destination/strategies/restore/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/providers/local-destination/strategies/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/providers/local-destination/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/providers/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/index.js
- /opt/app/node_modules/@strapi/strapi/lib/commands/utils/data-transfer.js
- /opt/app/node_modules/@strapi/strapi/lib/commands/actions/export/command.js
- /opt/app/node_modules/@strapi/strapi/lib/commands/index.js
- /opt/app/node_modules/@strapi/strapi/bin/strapi.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
Error: Could not load js config file /opt/app/node_modules/@strapi/plugin-upload/strapi-server.js:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linuxmusl-x64.node'
Require stack:
- /opt/app/node_modules/sharp/lib/sharp.js
- /opt/app/node_modules/sharp/lib/constructor.js
- /opt/app/node_modules/sharp/lib/index.js
- /opt/app/node_modules/@strapi/plugin-upload/server/services/image-manipulation.js
- /opt/app/node_modules/@strapi/plugin-upload/server/services/index.js
- /opt/app/node_modules/@strapi/plugin-upload/server/index.js
- /opt/app/node_modules/@strapi/plugin-upload/strapi-server.js
- /opt/app/node_modules/@strapi/utils/dist/import-default.js
- /opt/app/node_modules/@strapi/utils/dist/index.js
- /opt/app/node_modules/@strapi/strapi/lib/services/entity-service/components.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/queries/entity.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/queries/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/providers/local-destination/strategies/restore/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/providers/local-destination/strategies/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/providers/local-destination/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/providers/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/strapi/index.js
- /opt/app/node_modules/@strapi/data-transfer/dist/index.js
- /opt/app/node_modules/@strapi/strapi/lib/commands/utils/data-transfer.js
- /opt/app/node_modules/@strapi/strapi/lib/commands/actions/export/command.js
- /opt/app/node_modules/@strapi/strapi/lib/commands/index.js
- /opt/app/node_modules/@strapi/strapi/bin/strapi.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at loadJsFile (/opt/app/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:18:11)
    at loadFile (/opt/app/node_modules/@strapi/strapi/lib/core/app-configuration/load-config-file.js:35:14)
    at Object.loadPlugins (/opt/app/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:103:26)
    at async Strapi.loadPlugins (/opt/app/node_modules/@strapi/strapi/lib/Strapi.js:352:5)
    at async Promise.all (index 3)
    at async Strapi.register (/opt/app/node_modules/@strapi/strapi/lib/Strapi.js:392:5)
    at async Strapi.load (/opt/app/node_modules/@strapi/strapi/lib/Strapi.js:503:5)
    at async Strapi.start (/opt/app/node_modules/@strapi/strapi/lib/Strapi.js:224:9)
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: strapi-cms@0.0.0
npm ERR!   at location: /opt/app/apps/strapi-cms
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.2.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.3>
npm notice Run `npm install -g npm@10.2.3` to update!
npm notice

**Comment by maurodandrea** [comment]
If we remove the "extends" line from the /apps/strapi-cms/tsconfig.json and from /apps/strapi-cms/src/admin/tsconfig.json files and add them the lines exixst in the "compilerOptions" section of the tsconfig.json of the repo root, leaving everything as it is in the main branch and using the flow and docker file in the "DeployCMS" branch (PR: https://github.com/pagopa/b2b-portals/pull/33), build and run work fine. 
image


Tested on AWS DGS cloud:
image

**Comment by maurodandrea** [comment]
I solved the problem (dependency from tsconfig of root repo)  with the modify contained in PR (https://github.com/pagopa/b2b-portals/pull/33): updated workflow, dockerfile and dockerignore

**Pull request closed without merging**
